/**
 * Build-time sitemap generator.
 *
 * Replaces the old hand-maintained public/sitemap.xml, which drifted out of
 * sync (it silently omitted /blogs, /careers, /scouts and /napkin-rothenhall
 * and pinned every <lastmod> to one date).
 *
 * How it stays correct on its own:
 *   - It discovers every static marketing page by scanning src/routes/*.tsx
 *     for the `path: '/...'` literal passed to the seo() helper. Add a new
 *     route that calls seo() and it appears here automatically — no editing.
 *   - It skips dynamic routes (any file with a `$` param, e.g. blog.$slug) and
 *     the root layout. Blog posts are published by the separate, DB-driven
 *     /blog-sitemap.xml (see api/blog-sitemap.get.ts), also referenced in
 *     robots.txt.
 *   - It skips any route that marks itself `noindex` — currently /founders,
 *     /terms and /napkin-rothenhall.
 *   - <lastmod> comes from each route file's last git commit date, falling back
 *     to the file mtime, then to the build date.
 *
 * Run automatically as the first step of `npm run build`. It also runs standalone
 * (`npm run gen:sitemap`) to refresh the committed file for local dev.
 */
import { readdirSync, readFileSync, existsSync, statSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const routesDir = `${root}src/routes`
const outPath = `${root}public/sitemap.xml`
const SITE_URL = 'https://www.rothenhall.com'

// Optional per-path SEO hints; everything else gets sensible defaults.
const OVERRIDES = {
  '/': { priority: '1.0', changefreq: 'weekly' },
  '/cailyx': { priority: '0.9' },
  '/pricing': { priority: '0.9' },
  '/research': { priority: '0.9' },
  '/ai-visibility-score': { priority: '0.9' },
  '/about': { priority: '0.7' },
}

function isoDay(date) {
  return new Date(date).toISOString().slice(0, 10)
}

function lastmodFor(absFile) {
  try {
    const out = execFileSync(
      'git',
      ['-C', root, 'log', '-1', '--format=%cI', '--', absFile],
      { encoding: 'utf8' },
    ).trim()
    if (out) return out.slice(0, 10)
  } catch {
    /* git unavailable in this build environment */
  }
  if (existsSync(absFile)) {
    try {
      return isoDay(statSync(absFile).mtimeMs)
    } catch {
      /* ignore */
    }
  }
  return isoDay(Date.now())
}

// path -> { file } for the route that owns it.
const pages = new Map()

for (const name of readdirSync(routesDir).sort()) {
  if (!name.endsWith('.tsx')) continue
  if (name === '__root.tsx') continue
  if (name.includes('$')) continue // dynamic segments live in a sub-sitemap

  const file = `${routesDir}/${name}`
  const src = readFileSync(file, 'utf8')

  // Collect the literal `path: '/...'` strings handed to seo().
  const literalPaths = [...src.matchAll(/path:\s*'\/([^']*)'/g)].map(
    (m) => '/' + m[1],
  )
  if (literalPaths.length === 0) continue

  // Skip any route whose head ships a noindex robots meta. This also catches
  // napkin-rothenhall, whose head overwrites the robots meta to noindex even on
  // the default route, so it correctly stays out of the sitemap.
  if (/robots['"]?\s*,?\s*content:\s*['"]noindex/.test(src)) continue

  for (const p of literalPaths) {
    if (!pages.has(p)) pages.set(p, file)
  }
}

// Home first, then alphabetical.
const ordered = [...pages.keys()].sort((a, b) => {
  if (a === '/') return -1
  if (b === '/') return 1
  return a.localeCompare(b)
})

const body = ordered
  .map((p) => {
    const file = pages.get(p)
    const o = OVERRIDES[p] || {}
    const loc = p === '/' ? `${SITE_URL}/` : `${SITE_URL}${p}`
    return [
      '  <url>',
      `    <loc>${loc}</loc>`,
      `    <lastmod>${lastmodFor(file)}</lastmod>`,
      `    <changefreq>${o.changefreq || 'monthly'}</changefreq>`,
      `    <priority>${o.priority || '0.8'}</priority>`,
      '  </url>',
    ].join('\n')
  })
  .join('\n')

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`

writeFileSync(outPath, xml, 'utf8')
console.log(
  `[sitemap] wrote ${ordered.length} marketing URLs to public/sitemap.xml`,
)

/* ------------------------------------------------------------------ */
/*  IndexNow: push marketing URLs so Bing/Copilot re-crawl on deploy  */
/* ------------------------------------------------------------------ */
const INDEXNOW_KEY =
  process.env.INDEXNOW_KEY || '60bed373bbd04097b3ba237d4d6a169a'
const HOST = 'www.rothenhall.com'
const urlList = ordered.map((p) => (p === '/' ? `${SITE_URL}/` : `${SITE_URL}${p}`))

if (!process.env.INDEXNOW_SKIP) {
  try {
    const res = await fetch('https://api.indexnow.org/indexnow', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body: JSON.stringify({
        host: HOST,
        key: INDEXNOW_KEY,
        keyLocation: `https://${HOST}/${INDEXNOW_KEY}.txt`,
        urlList,
      }),
    })
    console.log(
      `[indexnow] submitted ${urlList.length} marketing URL(s) — HTTP ${res.status}`,
    )
  } catch (err) {
    // Non-fatal: a search-engine ping must never break the build.
    console.warn(
      '[indexnow] build-time ping failed (non-fatal):',
      err instanceof Error ? err.message : err,
    )
  }
}
