/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AeoVsSeoRouteImport } from './routes/aeo-vs-seo'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as CailyxRouteImport } from './routes/cailyx'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as HowToShowUpInChatgptRouteImport } from './routes/how-to-show-up-in-chatgpt'
import { Route as ResearchRouteImport } from './routes/research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoVsSeoRoute = AeoVsSeoRouteImport.update({
  id: '/aeo-vs-seo',
  path: '/aeo-vs-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const CailyxRoute = CailyxRouteImport.update({
  id: '/cailyx',
  path: '/cailyx',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToShowUpInChatgptRoute = HowToShowUpInChatgptRouteImport.update({
  id: '/how-to-show-up-in-chatgpt',
  path: '/how-to-show-up-in-chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aeo-vs-seo': typeof AeoVsSeoRoute
  '/approach': typeof ApproachRoute
  '/cailyx': typeof CailyxRoute
  '/case-studies': typeof CaseStudiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/how-to-show-up-in-chatgpt': typeof HowToShowUpInChatgptRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aeo-vs-seo': typeof AeoVsSeoRoute
  '/approach': typeof ApproachRoute
  '/cailyx': typeof CailyxRoute
  '/case-studies': typeof CaseStudiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/how-to-show-up-in-chatgpt': typeof HowToShowUpInChatgptRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aeo-vs-seo': typeof AeoVsSeoRoute
  '/approach': typeof ApproachRoute
  '/cailyx': typeof CailyxRoute
  '/case-studies': typeof CaseStudiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/how-to-show-up-in-chatgpt': typeof HowToShowUpInChatgptRoute
  '/research': typeof ResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aeo-vs-seo'
    | '/approach'
    | '/cailyx'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/faq'
    | '/founders'
    | '/how-to-show-up-in-chatgpt'
    | '/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aeo-vs-seo'
    | '/approach'
    | '/cailyx'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/faq'
    | '/founders'
    | '/how-to-show-up-in-chatgpt'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aeo-vs-seo'
    | '/approach'
    | '/cailyx'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/faq'
    | '/founders'
    | '/how-to-show-up-in-chatgpt'
    | '/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AeoVsSeoRoute: typeof AeoVsSeoRoute
  ApproachRoute: typeof ApproachRoute
  CailyxRoute: typeof CailyxRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FoundersRoute: typeof FoundersRoute
  HowToShowUpInChatgptRoute: typeof HowToShowUpInChatgptRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-vs-seo': {
      id: '/aeo-vs-seo'
      path: '/aeo-vs-seo'
      fullPath: '/aeo-vs-seo'
      preLoaderRoute: typeof AeoVsSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cailyx': {
      id: '/cailyx'
      path: '/cailyx'
      fullPath: '/cailyx'
      preLoaderRoute: typeof CailyxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-show-up-in-chatgpt': {
      id: '/how-to-show-up-in-chatgpt'
      path: '/how-to-show-up-in-chatgpt'
      fullPath: '/how-to-show-up-in-chatgpt'
      preLoaderRoute: typeof HowToShowUpInChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AeoVsSeoRoute: AeoVsSeoRoute,
  ApproachRoute: ApproachRoute,
  CailyxRoute: CailyxRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FoundersRoute: FoundersRoute,
  HowToShowUpInChatgptRoute: HowToShowUpInChatgptRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
