/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AeoVsSeoRouteImport } from './routes/aeo-vs-seo'
import { Route as AiVisibilityScoreRouteImport } from './routes/ai-visibility-score'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CailyxRouteImport } from './routes/cailyx'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as HowToShowUpInChatgptRouteImport } from './routes/how-to-show-up-in-chatgpt'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoVsSeoRoute = AeoVsSeoRouteImport.update({
  id: '/aeo-vs-seo',
  path: '/aeo-vs-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisibilityScoreRoute = AiVisibilityScoreRouteImport.update({
  id: '/ai-visibility-score',
  path: '/ai-visibility-score',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CailyxRoute = CailyxRouteImport.update({
  id: '/cailyx',
  path: '/cailyx',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToShowUpInChatgptRoute = HowToShowUpInChatgptRouteImport.update({
  id: '/how-to-show-up-in-chatgpt',
  path: '/how-to-show-up-in-chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aeo-vs-seo': typeof AeoVsSeoRoute
  '/ai-visibility-score': typeof AiVisibilityScoreRoute
  '/blogs': typeof BlogsRoute
  '/cailyx': typeof CailyxRoute
  '/case-studies': typeof CaseStudiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/how-to-show-up-in-chatgpt': typeof HowToShowUpInChatgptRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aeo-vs-seo': typeof AeoVsSeoRoute
  '/ai-visibility-score': typeof AiVisibilityScoreRoute
  '/blogs': typeof BlogsRoute
  '/cailyx': typeof CailyxRoute
  '/case-studies': typeof CaseStudiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/how-to-show-up-in-chatgpt': typeof HowToShowUpInChatgptRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aeo-vs-seo': typeof AeoVsSeoRoute
  '/ai-visibility-score': typeof AiVisibilityScoreRoute
  '/blogs': typeof BlogsRoute
  '/cailyx': typeof CailyxRoute
  '/case-studies': typeof CaseStudiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/how-to-show-up-in-chatgpt': typeof HowToShowUpInChatgptRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aeo-vs-seo'
    | '/ai-visibility-score'
    | '/blogs'
    | '/cailyx'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/faq'
    | '/founders'
    | '/how-to-show-up-in-chatgpt'
    | '/pricing'
    | '/research'
    | '/terms'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aeo-vs-seo'
    | '/ai-visibility-score'
    | '/blogs'
    | '/cailyx'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/faq'
    | '/founders'
    | '/how-to-show-up-in-chatgpt'
    | '/pricing'
    | '/research'
    | '/terms'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aeo-vs-seo'
    | '/ai-visibility-score'
    | '/blogs'
    | '/cailyx'
    | '/case-studies'
    | '/community'
    | '/contact'
    | '/faq'
    | '/founders'
    | '/how-to-show-up-in-chatgpt'
    | '/pricing'
    | '/research'
    | '/terms'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AeoVsSeoRoute: typeof AeoVsSeoRoute
  AiVisibilityScoreRoute: typeof AiVisibilityScoreRoute
  BlogsRoute: typeof BlogsRoute
  CailyxRoute: typeof CailyxRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FoundersRoute: typeof FoundersRoute
  HowToShowUpInChatgptRoute: typeof HowToShowUpInChatgptRoute
  PricingRoute: typeof PricingRoute
  ResearchRoute: typeof ResearchRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-vs-seo': {
      id: '/aeo-vs-seo'
      path: '/aeo-vs-seo'
      fullPath: '/aeo-vs-seo'
      preLoaderRoute: typeof AeoVsSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-score': {
      id: '/ai-visibility-score'
      path: '/ai-visibility-score'
      fullPath: '/ai-visibility-score'
      preLoaderRoute: typeof AiVisibilityScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cailyx': {
      id: '/cailyx'
      path: '/cailyx'
      fullPath: '/cailyx'
      preLoaderRoute: typeof CailyxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-show-up-in-chatgpt': {
      id: '/how-to-show-up-in-chatgpt'
      path: '/how-to-show-up-in-chatgpt'
      fullPath: '/how-to-show-up-in-chatgpt'
      preLoaderRoute: typeof HowToShowUpInChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AeoVsSeoRoute: AeoVsSeoRoute,
  AiVisibilityScoreRoute: AiVisibilityScoreRoute,
  BlogsRoute: BlogsRoute,
  CailyxRoute: CailyxRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FoundersRoute: FoundersRoute,
  HowToShowUpInChatgptRoute: HowToShowUpInChatgptRoute,
  PricingRoute: PricingRoute,
  ResearchRoute: ResearchRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
